/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute([
  {url:'favicon.ico', revision: null},
{url:'index.html', revision: null},
{url:'.DS_Store', revision: null},
{url:'manifest.json', revision: null},
{url:'serviceworker.js', revision: null},
{url:'robots.txt', revision: null},
{url:'assets/bootstrap/css/bootstrap.min.css', revision: null},
{url:'assets/bootstrap/js/bootstrap.min.js', revision: null},
{url:'assets/css/Brewing_Guide2.css', revision: null},
{url:'assets/css/Coffee_Article.css', revision: null},
{url:'assets/css/Community.css', revision: null},
{url:'assets/css/Brewing_Guide3.css', revision: null},
{url:'assets/css/Brewing_Guide4.css', revision: null},
{url:'assets/css/styles.css', revision: null},
{url:'assets/css/Features-Clean.css', revision: null},
{url:'assets/css/Multiple-Input-Select-Pills.css', revision: null},
{url:'assets/css/Ultimate-Sidebar-Menu-BS5.css', revision: null},
{url:'assets/css/Round_switch.css', revision: null},
{url:'assets/css/Profile_page.css', revision: null},
{url:'assets/css/Error.css', revision: null},
{url:'assets/css/Login_Register.css', revision: null},
{url:'assets/css/Brewing_Guide.css', revision: null},
{url:'assets/css/Admin_page.css', revision: null},
{url:'assets/js/CoffeeProject.js', revision: null},
{url:'assets/js/CoffeeAvarta.js', revision: null},
{url:'assets/js/bs-init.js', revision: null},
{url:'assets/img/pwaicon512.png', revision: null},
{url:'assets/img/legend_water.png', revision: null},
{url:'assets/img/MokaPot.png', revision: null},
{url:'assets/img/Tools_5.png', revision: null},
{url:'assets/img/Tools_4.png', revision: null},
{url:'assets/img/Error2.png', revision: null},
{url:'assets/img/Favorite Icon.png', revision: null},
{url:'assets/img/legend_rename.png', revision: null},
{url:'assets/img/Moka_ICO.png', revision: null},
{url:'assets/img/Tools_6.png', revision: null},
{url:'assets/img/Tools_7.png', revision: null},
{url:'assets/img/Error1.png', revision: null},
{url:'assets/img/Tools_3.png', revision: null},
{url:'assets/img/Tools_2.png', revision: null},
{url:'assets/img/guide_pack_ico.png', revision: null},
{url:'assets/img/Hario_ICO.png', revision: null},
{url:'assets/img/guide_ratio_ico.png', revision: null},
{url:'assets/img/Tools_1.png', revision: null},
{url:'assets/img/Frenchpress_ICO.png', revision: null},
{url:'assets/img/AvatarIcon.jpg', revision: null},
{url:'assets/img/guide_water_ico.png', revision: null},
{url:'assets/img/guide_timer_ico.png', revision: null},
{url:'assets/img/Process_Dummy_icon.png', revision: null},
{url:'assets/img/Shop Icon.png', revision: null},
{url:'assets/img/legend_name.png', revision: null},
{url:'assets/img/legend_picture.png', revision: null},
{url:'assets/img/Aeropress_ICO.png', revision: null},
{url:'assets/img/legend_process.png', revision: null},
{url:'assets/img/Chemex.png', revision: null},
{url:'assets/img/guide_bean_ico.png', revision: null},
{url:'assets/img/Timer_pause_ico.png', revision: null},
{url:'assets/img/Article_Dummy.png', revision: null},
{url:'assets/img/Timer_play_ico.png', revision: null},
{url:'assets/img/Frenchpress.png', revision: null},
{url:'assets/img/legend_note.png', revision: null},
{url:'assets/img/legend_time.png', revision: null},
{url:'assets/img/legend_bean.png', revision: null},
{url:'assets/img/Comment_Female.png', revision: null},
{url:'assets/img/guide_grind_ico.png', revision: null},
{url:'assets/img/BG1.png', revision: null},
{url:'assets/img/Aeropress192.png', revision: null},
{url:'assets/img/guide_heat_ico.png', revision: null},
{url:'assets/img/ALL_ICO.png', revision: null},
{url:'assets/img/Sample.png', revision: null},
{url:'assets/img/Mug icon.png', revision: null},
{url:'assets/img/pwaicon192.png', revision: null},
{url:'assets/img/Shop_Dummy.png', revision: null},
{url:'assets/img/legend_tool.png', revision: null},
{url:'assets/img/Timer_skip_ico.png', revision: null},
{url:'assets/img/CoffeeCactus.png', revision: null},
{url:'assets/img/Mainprofile3.jpg', revision: null},
{url:'assets/img/Picture1.png', revision: null},
{url:'assets/img/Finished_ICO1.gif', revision: null},
{url:'assets/img/Mainprofile2.png', revision: null},
{url:'assets/img/Tools_10.png', revision: null},
{url:'assets/img/Comment_Male.png', revision: null},
{url:'assets/img/Cup Icon.png', revision: null},
{url:'assets/img/Picture3.png', revision: null},
{url:'assets/img/5sec.mp3', revision: null},
{url:'assets/img/Mainprofile1.jpg', revision: null},
{url:'assets/img/Chemex_ICO.png', revision: null},
{url:'assets/img/Tools_11.png', revision: null},
{url:'assets/img/Mainprofile5.png', revision: null},
{url:'assets/img/Hario V60.png', revision: null},
{url:'assets/img/Finished_text.gif', revision: null},
{url:'assets/img/Mainprofile4.png', revision: null},
{url:'assets/img/Tools_9.png', revision: null},
{url:'assets/img/Tools_8.png', revision: null},
{url:'assets/img/Aeropress.png', revision: null},
{url:'assets/fonts/fa-solid-900.ttf', revision: null},
{url:'assets/fonts/fontawesome-webfont.svg', revision: null},
{url:'assets/fonts/MaterialIcons-Regular.svg', revision: null},
{url:'assets/fonts/fontawesome5-overrides.min.css', revision: null},
{url:'assets/fonts/FontAwesome.otf', revision: null},
{url:'assets/fonts/fa-regular-400.svg', revision: null},
{url:'assets/fonts/ionicons.eot', revision: null},
{url:'assets/fonts/fa-regular-400.woff2', revision: null},
{url:'assets/fonts/ionicons.woff', revision: null},
{url:'assets/fonts/MaterialIcons-Regular.woff2', revision: null},
{url:'assets/fonts/fa-solid-900.eot', revision: null},
{url:'assets/fonts/ionicons.ttf', revision: null},
{url:'assets/fonts/fontawesome-all.min.css', revision: null},
{url:'assets/fonts/fontawesome-webfont.woff2', revision: null},
{url:'assets/fonts/fa-brands-400.svg', revision: null},
{url:'assets/fonts/material-icons.min.css', revision: null},
{url:'assets/fonts/fa-regular-400.woff', revision: null},
{url:'assets/fonts/fa-brands-400.eot', revision: null},
{url:'assets/fonts/MaterialIcons-Regular.woff', revision: null},
{url:'assets/fonts/fa-solid-900.svg', revision: null},
{url:'assets/fonts/fontawesome-webfont.ttf', revision: null},
{url:'assets/fonts/ionicons.min.css', revision: null},
{url:'assets/fonts/MaterialIcons-Regular.ttf', revision: null},
{url:'assets/fonts/font-awesome.min.css', revision: null},
{url:'assets/fonts/fa-solid-900.woff', revision: null},
{url:'assets/fonts/fa-regular-400.ttf', revision: null},
{url:'assets/fonts/ionicons.svg', revision: null},
{url:'assets/fonts/fontawesome-webfont.woff', revision: null},
{url:'assets/fonts/fa-solid-900.woff2', revision: null},
{url:'assets/fonts/fa-brands-400.woff2', revision: null},
{url:'assets/fonts/fa-brands-400.woff', revision: null},
{url:'assets/fonts/fa-brands-400.ttf', revision: null},
{url:'assets/fonts/fontawesome-webfont.eot', revision: null},
{url:'assets/fonts/MaterialIcons-Regular.eot', revision: null},
{url:'assets/fonts/fa-regular-400.eot', revision: null},
  // ... other entries ...
]);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
